version: '3'
services:
  RPPS_RobertoWeb:
       image: bpmspace/rpps-apache-php
       ports:
            - $Port_Pizza_Team_web:443
       volumes:
         - './webroot/:/var/www/html/'
         - './internal/internal_${Number_Pizza_Team}/:/var/www/html/internal'
         - './dockerconf/apache2/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf'
         - './dockerconf/apache2/certbot.pem:/etc/ssl/certs/certbot.pem'
         - './dockerconf/apache2/certbot_priv.pem:/etc/ssl/certs/certbot_priv.pem'
       environment:
        - Number_Pizza_Team=${Number_Pizza_Team}
        - Passwd_Pizza_Team_DB=${Passwd_Pizza_Team_DB}
        - Port_Pizza_Team_DB=${Port_Pizza_Team_DB}
        - Port_Pizza_Team_PHPADMIN=${Port_Pizza_Team_PHPADMIN}
        - Port_Pizza_Team_web=${Port_Pizza_Team_web}

       links:
        -  RPPS_mariadb10
  RPPS_mariadb10:
        image: mariadb:latest
        ports:
        - ${Port_Pizza_Team_DB}:3306
        command: [mysqld, --default-authentication-plugin=mysql_native_password, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
        volumes:
        - ./mariadb10/mariadb10_${Number_Pizza_Team}:/var/lib/mysql
        environment:
        - MYSQL_ROOT_PASSWORD=${Passwd_Pizza_Team_DB}
        - MYSQL_DATABASE=RPPS
        - MYSQL_USER=RPPS
        - MYSQL_PASSWORD=${Passwd_Pizza_Team_DB}
        - TZ=Europe/Berlin
        working_dir: /root/import
  RPPS_phpmyadmin-mariadb:
        image: phpmyadmin/phpmyadmin:latest
        ports:
        - ${Port_Pizza_Team_PHPADMIN}:80
        volumes:
        - ./dockerconf/htaccess/.htaccess:/var/www/html/.htaccess
        - ./dockerconf/htaccess/.htpasswd:/htaccess/.htpasswd
        depends_on:
        - RPPS_mariadb10
        working_dir: /etc/phpmyadmin/
        environment:
        - PMA_HOST=RPPS_mariadb10
        - PMA_PORT=3306 
        - PMA_USER=root
        - PMA_PASSWORD=${Passwd_Pizza_Team_DB}
  sftp:
    image: atmoz/sftp
    volumes:
        - './internal/internal_${Number_Pizza_Team}/service_OUT.inc.php:/home/team${Number_Pizza_Team}/service_OUT.inc.php'
        - './internal/internal_${Number_Pizza_Team}/kitchen_OUT.inc.php:/home/team${Number_Pizza_Team}/kitchen_OUT.inc.php'
        - './internal/internal_${Number_Pizza_Team}/delivery_OUT.inc.php:/home/team${Number_Pizza_Team}/delivery_OUT.inc.php'
    ports:
        - ${Port_Pizza_Team_ssh}:22
    command: team${Number_Pizza_Team}:PizzaRegina:1001:0
networks:
        default:
         external:
           name: SIM_RPPS.${Number_Pizza_Team}