version: '3'
services:
  ServiceDeskMail:
        image: mailhog/mailhog
        restart: always
        ports:
            - $Port_Pizza_Team_ServiceDesk:8025
  KitchenMail:
        image: mailhog/mailhog
        restart: always
        ports:
            - $Port_Pizza_Team_Kitchen:8025
  DriverMail:
        image: mailhog/mailhog
        restart: always
        ports:
            - $Port_Pizza_Team_Driver:8025
  RobertoWeb:
       image: bpmspace/rpps-apache-php
       ports:
            - $Port_Pizza_Team_web:443
       volumes:
         - './webroot/:/var/www/html/'
         - './internal/internal_${Number_Pizza_Team}/:/var/www/html/internal'
         - './dockerconf/apache2/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf'
         - './dockerconf/apache2/certbot.pem:/etc/ssl/certs/certbot.pem'
         - './dockerconf/apache2/certbot_priv.pem:/etc/ssl/certs/certbot_priv.pem'
       environment:
        - TEAM_NUMBER=${Number_Pizza_Team}
networks:
    default:
      external:
        name: pizza.${Number_Pizza_Team}