version: '3'
services:
  RPPS_mariadb10:
        image: mariadb:latest
        command: [mysqld, --default-authentication-plugin=mysql_native_password, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
        volumes:
        - ./mariadb10/:/var/lib/mysql
        environment:
        - MYSQL_ROOT_PASSWORD=RPPS1122
        - MYSQL_DATABASE=RPPS
        - MYSQL_USER=RPPS
        - MYSQL_PASSWORD=RPPS1122
        - TZ=Europe/Berlin
        working_dir: /root/import
  RPPS_phpmyadmin-mariadb:
        image: phpmyadmin/phpmyadmin:latest
        ports:
        - 6200:80
        depends_on:
        - RPPS_mariadb10
        working_dir: /etc/phpmyadmin/
        environment:
        - PMA_HOST=RPPS_mariadb10
        - PMA_PORT=3306 
networks:
        default:
         external:
           name: SIM_RPPS